"""tree-sitter AST chunking for the semantic index.

Splits source files at function/class boundaries (256-512 token target;
tokens approximated as len(text)//4, no tokenizer dependency). Every
chunk gets a `# file: <path>` (plus `# in class: <Parent>` when
applicable) context header attached as a final pass, after splitting and
merging. An oversized class splits into per-method chunks, each tagged
with its enclosing class name so the header can re-add that context. An
oversized function/non-class def (no natural sub-boundary to split into)
instead falls back to fixed overlapping windows over just its own text —
without this, a single long function ships as one unbounded chunk, which
can blow an embedding model's sequence-length/memory limits at encode
time. Unparseable files fall back to fixed overlapping windows over the
whole file.
tree_sitter_language_pack is imported lazily so a base install never
needs it.
"""

from __future__ import annotations

import hashlib
import subprocess
from dataclasses import dataclass
from pathlib import Path

from codeintel.config import IGNORED_DIRS

MAX_TOKENS = 512
MIN_TOKENS = 256
OVERLAP_TOKENS = 50

# Every chunk gets a context header appended by _apply_headers(). Splitting
# happens before that header exists, so the sizing paths reserve this
# allowance -- otherwise a chunk sized exactly at MAX_TOKENS would overflow
# the cap the moment its header lands.
HEADER_RESERVE_TOKENS = 32
_EFFECTIVE_MAX_TOKENS = MAX_TOKENS - HEADER_RESERVE_TOKENS

# Shape of the text stored in Chunk.content. Bump when that shape changes:
# semantic.py folds this into the table identity, so a bump invalidates every
# stored vector and forces a full re-chunk. Needed because unchanged files are
# matched by file_hash, not content_hash -- without a version, a file whose
# bytes never changed would carry its old-format rows forward forever.
CONTENT_FORMAT = 1

# Admission policy for the semantic index (the "Layer 4" pre-index filter).
# Generated and minified files are pure noise once embedded: they dominate
# chunk counts while carrying no searchable intent. They stay lexically
# searchable through the separate Zoekt pipeline, which indexes them anyway.
# Built via concatenation, not as plain literals: chunker.py is itself
# scanned by skip_reason() during semantic indexing, and a bare literal
# tuple here would make this file match its own generated-file filter.
# The runtime string values are unchanged — only the on-disk source no
# longer contains any marker as one contiguous substring.
GENERATED_BANNERS = ("auto" + "-generated", "@" + "generated",
                     "code" + " generated by", "do not" + " edit",
                     "do not modify" + " this file")
BANNER_SCAN_CHARS = 2048
MAX_LINE_CHARS = 5000
MAX_FILE_BYTES = 1_048_576   # 1 MB backstop for files that dodge the other rules

LANGUAGES = {".py": "python", ".ts": "typescript", ".tsx": "tsx",
             ".java": "java", ".kt": "kotlin", ".swift": "swift"}

_DEF_NODE_TYPES: dict[str, set[str]] = {
    "python": {"function_definition", "class_definition", "decorated_definition"},
    "typescript": {"function_declaration", "class_declaration", "method_definition"},
    "tsx": {"function_declaration", "class_declaration", "method_definition"},
    "java": {"method_declaration", "class_declaration", "interface_declaration"},
    "kotlin": {"function_declaration", "class_declaration"},
    "swift": {"function_declaration", "class_declaration", "protocol_declaration"},
}
_CLASS_NODE_TYPES = {"class_definition", "class_declaration",
                     "interface_declaration", "protocol_declaration"}
# Kotlin's grammar attaches no "name" field to class_declaration/function_declaration
# (verified by direct parse); the identifier is a plain positional child instead.
_IDENTIFIER_NODE_TYPES = {"type_identifier", "simple_identifier"}


@dataclass(frozen=True)
class Chunk:
    file_path: str          # repo-relative posix path
    start_line: int         # 1-indexed
    end_line: int           # 1-indexed, inclusive
    content: str
    symbol_name: str | None  # None for fixed-window chunks
    content_hash: str
    file_hash: str
    language: str
    parent_name: str | None = None   # enclosing class, for the context header


def _tokens(text: str) -> int:
    return len(text) // 4


def hash_file(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def language_for(path: Path) -> str | None:
    return LANGUAGES.get(path.suffix)


def _force_included(rel_path: str, include_prefixes: tuple[str, ...]) -> bool:
    """A prefix force-includes an exact file match, or anything strictly
    beneath it as a directory. The trailing-slash form is deliberate: a bare
    `rel_path.startswith("src/gen")` would also swallow `src/generated/`."""
    return any(rel_path == prefix or rel_path.startswith(prefix.rstrip("/") + "/")
               for prefix in include_prefixes)


def skip_reason(rel_path: str, source: str,
                include_prefixes: tuple[str, ...] = ()) -> str | None:
    """Should this file enter the semantic index? `None` admits it;
    otherwise a short tag naming the trigger, for the skip report.

    Force-include is checked first and short-circuits both rules, so an
    operator can always override a false positive."""
    if _force_included(rel_path, include_prefixes):
        return None
    head = source[:BANNER_SCAN_CHARS].lower()
    for marker in GENERATED_BANNERS:
        if marker in head:
            return f"banner:{marker}"
    for line in source.splitlines():
        if len(line) > MAX_LINE_CHARS:
            return f"long-line:{len(line)}"
    return None


def oversized_file_reason(size_bytes: int) -> str | None:
    """Checked from the file's stat() before read_bytes(), so a huge file is
    never read into memory just to be rejected. A pure backstop: banner and
    long-line detection already catch generated and minified content, leaving
    only the large-file-with-normal-lines shape for this rule."""
    if size_bytes > MAX_FILE_BYTES:
        return f"too-large:{size_bytes}"
    return None


def gitignored(repo_path: Path, rel_paths: list[str]) -> set[str]:
    """Which of `rel_paths` git ignores, via one batched subprocess.

    `git check-ignore` does not use the usual exit-code convention: 0 means
    some paths matched, 1 means none matched, and anything else is a real
    error. Treating non-zero as failure would silently disable filtering on
    every repo that happens to ignore nothing. Any genuine failure -- not a
    git repo, git absent, a hang -- degrades to "nothing ignored", so the
    worst case is indexing more, never less."""
    if not rel_paths:
        return set()
    try:
        result = subprocess.run(
            ["git", "-C", str(repo_path), "check-ignore", "--stdin"],
            input="\n".join(rel_paths), capture_output=True, text=True, timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return set()
    if result.returncode != 0:
        return set()
    return {line for line in result.stdout.splitlines() if line}


def iter_source_files(repo_path: Path) -> list[tuple[Path, str]]:
    files: list[tuple[Path, str]] = []
    for path in sorted(repo_path.rglob("*")):
        if any(part in IGNORED_DIRS for part in path.parts):
            continue
        if path.is_file() and path.suffix in LANGUAGES:
            files.append((path, path.relative_to(repo_path).as_posix()))
    ignored = gitignored(repo_path, [rel for _, rel in files])
    return [(path, rel) for path, rel in files if rel not in ignored]


def _make_chunk(rel_path: str, language: str, file_hash: str, content: str,
                start_line: int, end_line: int, symbol: str | None,
                parent: str | None = None) -> Chunk:
    return Chunk(file_path=rel_path, start_line=start_line, end_line=end_line,
                 content=content, symbol_name=symbol,
                 content_hash=hashlib.sha256(content.encode()).hexdigest(),
                 file_hash=file_hash, language=language, parent_name=parent)


def _chunk_header(rel_path: str, chunk: Chunk) -> str:
    """Path plus enclosing class. The chunk's own symbol name is deliberately
    omitted -- it is already the first line of the chunk's code, so repeating
    it spends budget without adding a matchable term. The parent class is a
    different case: a method split out of an oversized class no longer
    contains its class name anywhere."""
    lines = [f"# file: {rel_path}"]
    if chunk.parent_name:
        lines.append(f"# in class: {chunk.parent_name}")
    return "\n".join(lines)


def _apply_headers(chunks: list[Chunk], rel_path: str) -> list[Chunk]:
    """Attach the context header to every chunk, as the last step of
    chunk_file(). Deliberately a final pass rather than done at construction:
    _merge_small concatenates chunk contents, so a header attached earlier
    would appear twice inside a merged chunk."""
    return [
        _make_chunk(rel_path, c.language, c.file_hash,
                    f"{_chunk_header(rel_path, c)}\n\n{c.content}",
                    c.start_line, c.end_line, c.symbol_name, c.parent_name)
        for c in chunks
    ]


def _node_name(node) -> str | None:
    named = node.child_by_field_name("name")
    if named is not None:
        return named.text.decode("utf-8", errors="replace")
    for child in node.children:  # e.g. decorated_definition wraps the real def
        # Suffix check avoids false positives like "function_value_parameters" /
        # "function_body", which also contain the substring "function".
        if child.type.endswith(("_definition", "_declaration")) and (
            child.type in _CLASS_NODE_TYPES or "function" in child.type or "method" in child.type
        ):
            return _node_name(child)
    for child in node.children:  # grammars with no "name" field (e.g. kotlin)
        if child.type in _IDENTIFIER_NODE_TYPES:
            return child.text.decode("utf-8", errors="replace")
    return None


def _walk(node):
    for child in node.children:
        yield child
        yield from _walk(child)


def _window_lines(lines: list[str], base_line: int) -> list[tuple[str, int, int]]:
    """Split `lines` into MAX_TOKENS-sized windows with OVERLAP_TOKENS overlap,
    each returned as (text, start_line, end_line) with `base_line` as the
    1-indexed file line of `lines[0]`. Shared by whole-file fallback chunking
    and oversized-def splitting.

    A single line longer than the window (e.g. a minified/generated file's
    serialized-literal line) is first character-sliced into window-sized
    pieces, each still tagged with its original source line number -- so the
    greedy accumulation loop below only ever handles pieces already capped
    at the window size, and never has to special-case a line mid-window."""
    window_chars, overlap_chars = _EFFECTIVE_MAX_TOKENS * 4, OVERLAP_TOKENS * 4

    pieces: list[tuple[str, int]] = []  # (text, source_line_no)
    for idx, line in enumerate(lines):
        line_no = base_line + idx
        if len(line) + 1 > window_chars:
            pieces.extend((line[start:start + window_chars], line_no)
                          for start in range(0, len(line), window_chars))
        else:
            pieces.append((line, line_no))

    windows: list[tuple[str, int, int]] = []
    i, n = 0, len(pieces)
    while i < n:
        j, size = i, 0
        while j < n:
            piece_len = len(pieces[j][0]) + 1
            if size > 0 and size + piece_len > window_chars:
                break
            size += piece_len
            j += 1
            if size >= window_chars:
                break
        text = "\n".join(p for p, _ in pieces[i:j])
        windows.append((text, pieces[i][1], pieces[j - 1][1]))
        if j >= n:
            break
        back, osize = j, 0
        while back > i + 1 and osize < overlap_chars:
            back -= 1
            osize += len(pieces[back][0]) + 1
        i = back
    return windows


def _fixed_windows(rel_path: str, language: str, file_hash: str, source: str) -> list[Chunk]:
    lines = source.splitlines()
    if not lines:
        return []
    return [_make_chunk(rel_path, language, file_hash, text, start, end, None)
            for text, start, end in _window_lines(lines, base_line=1)]


def _split_oversized_def(node, text: str, rel_path: str, language: str, file_hash: str) -> list[Chunk]:
    """A function/non-class def that alone exceeds MAX_TOKENS has no natural
    sub-boundary (unlike a class, which splits into methods), so it falls
    back to fixed windows over just its own text. All resulting chunks share
    the def's symbol_name."""
    symbol = _node_name(node)
    lines = text.splitlines()
    base_line = node.start_point[0] + 1
    return [_make_chunk(rel_path, language, file_hash, chunk_text, start, end, symbol)
            for chunk_text, start, end in _window_lines(lines, base_line)]


def _split_class(node, source: str, rel_path: str, language: str,
                 file_hash: str) -> list[Chunk]:
    """Methods of an oversized class become their own chunks, tagged with the
    class name so _apply_headers can re-add that context later."""
    class_name = _node_name(node)
    methods = [n for n in _walk(node)
               if n.type in _DEF_NODE_TYPES[language] and n.type not in _CLASS_NODE_TYPES]
    if not methods:
        text = source[node.start_byte:node.end_byte]
        return [_make_chunk(rel_path, language, file_hash, text,
                            node.start_point[0] + 1, node.end_point[0] + 1, class_name)]
    chunks: list[Chunk] = []
    for m in methods:
        symbol = _node_name(m)
        text = source[m.start_byte:m.end_byte]
        if _tokens(text) > _EFFECTIVE_MAX_TOKENS:
            # A single method can itself exceed the cap -- window it the same
            # way an oversized top-level def would be.
            base_line = m.start_point[0] + 1
            chunks.extend(
                _make_chunk(rel_path, language, file_hash, piece, start, end,
                            symbol, class_name)
                for piece, start, end in _window_lines(text.splitlines(), base_line)
            )
        else:
            chunks.append(_make_chunk(rel_path, language, file_hash, text,
                                      m.start_point[0] + 1, m.end_point[0] + 1,
                                      symbol, class_name))
    return chunks


def _merge_small(chunks: list[Chunk]) -> list[Chunk]:
    merged: list[Chunk] = []
    for chunk in chunks:
        if (merged and _tokens(merged[-1].content) < MIN_TOKENS
                and merged[-1].end_line < chunk.start_line
                # Never merge across a parent boundary: a class's last method
                # is adjacent to the next top-level def, and merging them would
                # stamp "# in class: X" onto code that is not in X.
                and merged[-1].parent_name == chunk.parent_name
                # MAX_TOKENS is a hard cap; MIN_TOKENS is only a soft
                # preference -- never merge past the hard cap just to grow
                # a too-small chunk.
                and _tokens(merged[-1].content) + _tokens(chunk.content)
                <= _EFFECTIVE_MAX_TOKENS):
            prev = merged.pop()
            merged.append(_make_chunk(chunk.file_path, chunk.language, chunk.file_hash,
                                      f"{prev.content}\n\n{chunk.content}",
                                      prev.start_line, chunk.end_line,
                                      prev.symbol_name or chunk.symbol_name,
                                      prev.parent_name))
        else:
            merged.append(chunk)
    return merged


def chunk_file(rel_path: str, source: str, file_hash: str, language: str) -> list[Chunk]:
    try:
        from tree_sitter_language_pack import get_parser
        tree = get_parser(language).parse(source.encode("utf-8"))
    except Exception:
        return _apply_headers(_fixed_windows(rel_path, language, file_hash, source), rel_path)

    root = tree.root_node
    defs = [n for n in root.children if n.type in _DEF_NODE_TYPES.get(language, set())]
    if not defs:
        return _apply_headers(_fixed_windows(rel_path, language, file_hash, source), rel_path)

    chunks: list[Chunk] = []
    for node in defs:
        text = source[node.start_byte:node.end_byte]
        target = node.children[-1] if node.type == "decorated_definition" else node
        if target.type in _CLASS_NODE_TYPES and _tokens(text) > _EFFECTIVE_MAX_TOKENS:
            chunks.extend(_split_class(target, source, rel_path, language, file_hash))
        elif _tokens(text) > _EFFECTIVE_MAX_TOKENS:
            chunks.extend(_split_oversized_def(node, text, rel_path, language, file_hash))
        else:
            chunks.append(_make_chunk(rel_path, language, file_hash, text,
                                      node.start_point[0] + 1, node.end_point[0] + 1,
                                      _node_name(node)))
    return _apply_headers(_merge_small(chunks), rel_path)
